from numpy.random import default_rng
from numpy import log2

rng = default_rng(seed=95)


#Obstacles
BOUNDARY_MARGIN = 20


#Vehicular
DEFAULT_VEHICLE_DENSITY = 0.02
VEH_SPEED_RANGE = [10, 15]
VEH_ANTENNA_HEIGHT = [1.5, 1.5]
SMALL_CYCLE_T = 1000
STREET_WIDTH = 12

#DBS
DBS_HEIGHT = 100
DBS_COVERAGE_LENGTH = 1321.54 #Most accurate MM vs SM from Bologna work
LOCS_DENSITIES_PER_STREET_LENGTH = 1/100

#BEAMS
N_BEAMS_PER_DBS = 9
BEAM_LENGTH = DBS_COVERAGE_LENGTH/N_BEAMS_PER_DBS

#Channel
CARRIER_FREQ = 27.5e9  #Hz
SPEED_OF_LIGHT = c=3*10**8 #[m/s], speed of light
SIGMA_SHADOWING = 4
TRANSMISSION_POWER = 5 #dBm
ANTENNA_GAIN = 0
NOISE_POWER = -93 #dBm
RECEIVER_SENSITIVITY = -55 #dBm
TOTAL_BANDWIDTH = 100e6 #Hz
REQUIRED_RATE = 100e6 #bps
REQUIRED_SNR = RECEIVER_SENSITIVITY - NOISE_POWER
K_0 = TOTAL_BANDWIDTH * log2(1 + REQUIRED_SNR)/REQUIRED_RATE